#pragma once

#define PROTOCOL_VERSION 340

#define CHAT_MSG_FROM_CLIENT_PACKETID 0x02
#define JOIN_GAME_PACKETID 0x23
#define KEEP_ALIVE_PACKETID 0x20
#define KEEP_ALIVE_CLIENT_PACKETID 0x1F
#define UPDATE_PLAYER_ANGLE_POS_PACKETID 0x2F
#define SPAWN_POSITION_PACKETID 0x46
#define SPAWN_PLAYER_PACKETID 0x05
#define SPAWN_MOB_PACKETID 0x03
#define PLAYER_INFO_PACKETID 0x33
#define CHAT_MSG_FROM_SERVER_PACKETID 0x0F
#define CHUNK_DATA_PACKETID 0x20


#define ENC_REQUEST_PACKETID 0x01
#define HANDSHAKE_PACKETID 0x00
#define LOGIN_SUCCESS_PACKETID 0x02
#define PING_PONG_PACKETID 0x01
#define STATUS_PACKETID 0x00